import 'package:cloud_firestore/cloud_firestore.dart';

/// Utility class to seed product data into Firestore.
/// Run once then remove.
class ProductSeeder {
  static final _firestore = FirebaseFirestore.instance;

  static Future<void> seedProducts() async {
    // First, get category IDs by name
    final catSnapshot = await _firestore.collection('categories').get();
    final Map<String, String> catNameToId = {};
    for (final doc in catSnapshot.docs) {
      final name = doc.data()['name'] as String? ?? '';
      catNameToId[name] = doc.data()['id'] as String? ?? doc.id;
    }

    final now = DateTime.now();

    final products = <Map<String, dynamic>>[
      // ── Quần Jeans ──
      {
        'name': 'Quần jeans skinny đen',
        'sku': 'QJ-001',
        'brand': "Levi's",
        'description': 'Quần jeans skinny fit màu đen trơn, chất denim co giãn thoải mái',
        'price': 890000.0,
        'salePrice': 690000.0,
        'categoryName': 'Quần Jeans',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Đen'],
        'material': 'Denim cotton 98%, Elastane 2%',
        'stock': 15,
      },
      {
        'name': 'Quần jeans rách gối',
        'sku': 'QJ-002',
        'brand': 'Zara',
        'description': 'Quần jeans rách gối phong cách vintage, wash nhẹ tạo hiệu ứng bạc màu',
        'price': 750000.0,
        'salePrice': null,
        'categoryName': 'Quần Jeans',
        'sizes': ['M', 'L', 'XL'],
        'colors': ['Xanh dương'],
        'material': 'Denim cotton 100%',
        'stock': 15,
      },
      {
        'name': 'Quần jeans ống rộng nữ',
        'sku': 'QJ-003',
        'brand': 'H&M',
        'description': 'Quần jeans ống rộng high-waist, tôn dáng, phù hợp mix đồ đa dạng',
        'price': 680000.0,
        'salePrice': 520000.0,
        'categoryName': 'Quần Jeans',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Xanh dương', 'Trắng'],
        'material': 'Denim cotton 99%, Spandex 1%',
        'stock': 15,
      },
      {
        'name': 'Quần jeans baggy nam',
        'sku': 'QJ-004',
        'brand': 'Local Brand',
        'description': 'Quần jeans baggy form rộng thoải mái, chất denim dày 12oz',
        'price': 550000.0,
        'salePrice': null,
        'categoryName': 'Quần Jeans',
        'sizes': ['M', 'L', 'XL', 'XXL'],
        'colors': ['Đen', 'Xanh dương'],
        'material': 'Denim cotton 100%',
        'stock': 15,
      },
      {
        'name': 'Quần jeans ống đứng',
        'sku': 'QJ-005',
        'brand': 'Calvin Klein',
        'description': 'Quần jeans straight fit cao cấp, đường may tinh xảo, wash trung',
        'price': 1200000.0,
        'salePrice': 950000.0,
        'categoryName': 'Quần Jeans',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Xanh dương', 'Đen'],
        'material': 'Denim cotton 97%, Elastane 3%',
        'stock': 15,
      },

      // ── Giày Sneaker ──
      {
        'name': "Air Force 1 '07 trắng",
        'sku': 'GS-001',
        'brand': 'Nike',
        'description': 'Giày sneaker cổ thấp huyền thoại, đế Air êm ái, da tổng hợp bền bỉ',
        'price': 2929000.0,
        'salePrice': null,
        'categoryName': 'Giày Sneaker',
        'sizes': ['M', 'L', 'XL'],
        'colors': ['Trắng'],
        'material': 'Da tổng hợp, Đế cao su',
        'stock': 15,
      },
      {
        'name': 'Stan Smith xanh lá',
        'sku': 'GS-002',
        'brand': 'Adidas',
        'description': 'Giày sneaker cổ điển, chất liệu da Primegreen thân thiện môi trường',
        'price': 2500000.0,
        'salePrice': 1990000.0,
        'categoryName': 'Giày Sneaker',
        'sizes': ['M', 'L', 'XL'],
        'colors': ['Trắng', 'Xanh lá'],
        'material': 'Da Primegreen tái chế',
        'stock': 15,
      },
      {
        'name': 'Old Skool đen trắng',
        'sku': 'GS-003',
        'brand': 'Vans',
        'description': 'Giày sneaker cổ thấp với sọc jazz signature, đế waffle bám tốt',
        'price': 1750000.0,
        'salePrice': null,
        'categoryName': 'Giày Sneaker',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Đen', 'Trắng'],
        'material': 'Vải canvas, Da lộn',
        'stock': 15,
      },
      {
        'name': 'Chuck Taylor All Star',
        'sku': 'GS-004',
        'brand': 'Converse',
        'description': 'Giày canvas kinh điển, đế cao su vulcanized, phù hợp mọi phong cách',
        'price': 1500000.0,
        'salePrice': 1200000.0,
        'categoryName': 'Giày Sneaker',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Đen', 'Trắng', 'Đỏ'],
        'material': 'Vải canvas, Đế cao su',
        'stock': 15,
      },
      {
        'name': 'RS-X Reinvention',
        'sku': 'GS-005',
        'brand': 'Puma',
        'description': 'Giày sneaker chunky retro-futuristic, đệm RS êm ái, phối màu nổi bật',
        'price': 2800000.0,
        'salePrice': 2200000.0,
        'categoryName': 'Giày Sneaker',
        'sizes': ['M', 'L', 'XL'],
        'colors': ['Trắng', 'Đen', 'Cam'],
        'material': 'Mesh, Da tổng hợp',
        'stock': 15,
      },

      // ── Áo Khoác ──
      {
        'name': 'Áo khoác hoodie zip',
        'sku': 'AK-001',
        'brand': 'Nike',
        'description': 'Áo hoodie kéo khóa full-zip, chất nỉ bông dày dặn, mũ trùm có dây rút',
        'price': 1200000.0,
        'salePrice': 950000.0,
        'categoryName': 'Áo Khoác',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Đen', 'Xám', 'Navy'],
        'material': 'Cotton 80%, Polyester 20%',
        'stock': 15,
      },
      {
        'name': 'Áo khoác bomber MA-1',
        'sku': 'AK-002',
        'brand': 'Alpha Industries',
        'description': 'Áo khoác bomber phong cách quân đội, lót màu cam cổ điển, chống gió tốt',
        'price': 1800000.0,
        'salePrice': null,
        'categoryName': 'Áo Khoác',
        'sizes': ['M', 'L', 'XL'],
        'colors': ['Đen', 'Xanh lá', 'Navy'],
        'material': 'Nylon 100%, Lót Polyester',
        'stock': 15,
      },
      {
        'name': 'Áo khoác jean wash',
        'sku': 'AK-003',
        'brand': "Levi's",
        'description': 'Áo khoác denim trucker jacket iconic, wash vintage, nút kim loại cao cấp',
        'price': 1500000.0,
        'salePrice': 1190000.0,
        'categoryName': 'Áo Khoác',
        'sizes': ['S', 'M', 'L', 'XL'],
        'colors': ['Xanh dương', 'Đen'],
        'material': 'Denim cotton 100%',
        'stock': 15,
      },
      {
        'name': 'Áo khoác gió nhẹ',
        'sku': 'AK-004',
        'brand': 'Uniqlo',
        'description': 'Áo khoác gió siêu nhẹ có thể gấp gọn, chống nước nhẹ, túi ẩn tiện lợi',
        'price': 790000.0,
        'salePrice': null,
        'categoryName': 'Áo Khoác',
        'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
        'colors': ['Đen', 'Navy', 'Xám'],
        'material': 'Nylon ripstop, Chống nước',
        'stock': 15,
      },
      {
        'name': 'Áo blazer oversize nữ',
        'sku': 'AK-005',
        'brand': 'Zara',
        'description': 'Áo blazer form rộng thanh lịch, vải tweed cao cấp, phù hợp đi làm và dạo phố',
        'price': 1350000.0,
        'salePrice': 1050000.0,
        'categoryName': 'Áo Khoác',
        'sizes': ['S', 'M', 'L'],
        'colors': ['Be', 'Đen', 'Nâu'],
        'material': 'Tweed Polyester 70%, Wool 30%',
        'stock': 15,
      },

      // ── Phụ Kiện ──
      {
        'name': 'Mũ lưỡi trai baseball cap',
        'sku': 'PK-001',
        'brand': 'New Era',
        'description': 'Mũ lưỡi trai 9FORTY, khóa snapback điều chỉnh, thêu logo phía trước',
        'price': 650000.0,
        'salePrice': 490000.0,
        'categoryName': 'Phụ Kiện',
        'sizes': ['M'],
        'colors': ['Đen', 'Trắng', 'Navy'],
        'material': 'Cotton twill 100%',
        'stock': 15,
      },
      {
        'name': 'Túi tote vải canvas',
        'sku': 'PK-002',
        'brand': 'Local Brand',
        'description': 'Túi tote vải canvas dày, in logo thêu, ngăn trong có khóa kéo',
        'price': 250000.0,
        'salePrice': null,
        'categoryName': 'Phụ Kiện',
        'sizes': ['M'],
        'colors': ['Đen', 'Be', 'Trắng'],
        'material': 'Canvas cotton 100%',
        'stock': 15,
      },
      {
        'name': 'Thắt lưng da bò thật',
        'sku': 'PK-003',
        'brand': 'Montblanc',
        'description': 'Thắt lưng da bò nguyên miếng, khóa kim loại mạ vàng, hộp quà tặng cao cấp',
        'price': 1800000.0,
        'salePrice': 1500000.0,
        'categoryName': 'Phụ Kiện',
        'sizes': ['M', 'L'],
        'colors': ['Đen', 'Nâu'],
        'material': 'Da bò thật 100%',
        'stock': 15,
      },
      {
        'name': 'Kính mát aviator',
        'sku': 'PK-004',
        'brand': 'Ray-Ban',
        'description': 'Kính mát aviator classic, tròng Polarized chống chói, gọng kim loại nhẹ',
        'price': 3200000.0,
        'salePrice': 2690000.0,
        'categoryName': 'Phụ Kiện',
        'sizes': ['M'],
        'colors': ['Đen', 'Vàng', 'Xám'],
        'material': 'Gọng kim loại, Tròng kính Polarized',
        'stock': 15,
      },
      {
        'name': 'Balo laptop 15.6 inch',
        'sku': 'PK-005',
        'brand': 'Herschel',
        'description': 'Balo đựng laptop 15.6", chất liệu polyester chống thấm, ngăn chính rộng rãi',
        'price': 1450000.0,
        'salePrice': null,
        'categoryName': 'Phụ Kiện',
        'sizes': ['L'],
        'colors': ['Đen', 'Xám', 'Navy'],
        'material': 'Polyester chống thấm',
        'stock': 15,
      },
    ];

    int count = 0;
    for (final p in products) {
      final catName = p['categoryName'] as String;
      final catId = catNameToId[catName] ?? '';

      final docRef = _firestore.collection('products').doc();
      final data = {
        'id': docRef.id,
        'name': p['name'],
        'description': p['description'],
        'sku': p['sku'],
        'brand': p['brand'],
        'price': p['price'],
        'salePrice': p['salePrice'],
        'categoryId': catId,
        'categoryName': catName,
        'imageUrl': null,
        'sizes': p['sizes'],
        'colors': p['colors'],
        'material': p['material'],
        'stock': p['stock'],
        'isActive': true,
        'createdAt': Timestamp.fromDate(now),
        'updatedAt': Timestamp.fromDate(now),
      };
      await docRef.set(data);
      count++;
    }
    print('✅ Seeded $count products successfully!');
  }
}
